//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieBooking
    {
        public int BookingId { get; set; }
        public Nullable<int> NumberofSeats { get; set; }
        public Nullable<int> Sid { get; set; }
        public Nullable<int> Mid { get; set; }
        public Nullable<int> TotalAmount { get; set; }
    
        public virtual Movietable Movietable { get; set; }
        public virtual ScreenTable ScreenTable { get; set; }
    }
}
