//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScreenTable()
        {
            this.MovieBookings = new HashSet<MovieBooking>();
        }
    
        public int ScreenId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Tid { get; set; }
        public Nullable<int> Mid { get; set; }
        public Nullable<int> NumberofSeats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieBooking> MovieBookings { get; set; }
        public virtual Movietable Movietable { get; set; }
        public virtual theatretable theatretable { get; set; }
    }
}
